# Generated by Django 3.1.7 on 2021-03-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortingAlgorithms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=30, verbose_name='алгоритм сортировки')),
            ],
            options={
                'verbose_name': 'Алгоритм',
                'verbose_name_plural': 'Алгоритмы',
            },
        ),
        migrations.CreateModel(
            name='SortingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='files_inputs', verbose_name='исходный файл')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorting.sortingalgorithms', verbose_name='алгоритм сортировки')),
            ],
        ),
        migrations.CreateModel(
            name='AddSorting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='время сортировки')),
                ('sorting_duration', models.CharField(max_length=30, verbose_name='длительность сортировки')),
                ('input_file', models.FileField(upload_to='files_inputs', verbose_name='исходный файл')),
                ('output_file', models.FileField(upload_to='files_outputs', verbose_name='результат сортировки')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorting.sortingalgorithms', verbose_name='алгоритм сортировки')),
            ],
            options={
                'verbose_name': 'Успешная сортировка',
                'verbose_name_plural': 'Успешные сортировки',
            },
        ),
    ]
