# Generated by Django 3.1.7 on 2021-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsorting',
            name='algorithm',
            field=models.CharField(max_length=50, verbose_name='алгоритм'),
        ),
    ]
