# Generated by Django 3.1.7 on 2021-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0007_auto_20210306_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortingform',
            name='input_file',
            field=models.FileField(upload_to='files_inputs', verbose_name='исходный файл'),
        ),
    ]
